### ISSUE TITLE
Document "multi sort" operations in LineUp

### ISSUE THREAD

**Issue by waxlamp** [arclamp/materialnet#120]
e.g., sort first by synthesis probability, then some other value.

**Comment by sgratzl** [comment]
this is a standard feature of LineUp. Several ways to to that:
 1. instead of click on the sort icon, use ctrl+click which makes it an additional one
 2. in case of the side bar, use the side bar sort criteria widget to add another one
 3. use the column menu (...) -> Sort By ... -> Ascending/Descending and specify the sort hierarchy priority

**Comment by waxlamp** [comment]
Thanks for the clarification. I will reassign this to myself and make it part of the "provide tooltips" issue (#122).
